import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  profileFormContainer: {
    paddingHorizontal: 20,
  },
  input: {
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    padding: 16,
    fontSize: 16,
    marginBottom: 16,
  },
  customMovieDetailsContainer: {
    alignItems: 'center',
    justifyContent: 'flex-start',
    width: 250,
    height: 450,
    backgroundColor: '#FFFFFF',
    borderRadius: 10,
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
    gap: 0,
    marginBottom: 0,
    paddingTop: 0,
  },
  customMovieImage: {
    width: '100%',
    height: 300,
    borderBottomLeftRadius: 0,
    borderBottomRightRadius: 0,
  },
  selectedSearchResultOutline: {
    shadowColor: '#FF5F6D',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.6,
    shadowRadius: 10,
    elevation: 8,
  },
  movieWrapper: {
    position: 'relative',
  },
  checkmarkOverlay: {
    position: 'absolute',
    top: 8,
    right: 8,
    zIndex: 10,
  },
  checkmarkCircle: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#FF5F6D',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 5,
  },
});
